[tool.poetry]
name = "setup-python"
version = "1.0.0"
description = "Scaffold for new python projects"
authors = ["Justin Chiou <chiou.kai@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/shadowlion/setup-python"
repository = "https://github.com/shadowlion/setup-python"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
pytest-cov = "^2.9.0"
nox = "^2020.5.24"
coverage = {version = "^5.1", extras = ["toml"]}

[tool.coverage.paths]
source = ["core", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["core"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

